name: Build Tuinity
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 16 ]
      fail-fast: true
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
      - name: Configure Git
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Actions"
      - name: Patch Tuinity
        run: |
          ./gradlew applyPatches --stacktrace --no-daemon
      - name: Build Tuinity
        run: |
          ./gradlew build --stacktrace --no-daemon
          ./gradlew paperclipJar --stacktrace --no-daemon
      - name: Archive Tuinity Paperclip
        uses: actions/upload-artifact@v2
        with:
          name: Tuinity
          path: tuinity-paperclip.jar
      - name: Set outputs
        id: short_sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          files: "./*.jar"
          body: |
            Commit ${{ steps.short_sha.outputs.sha_short }}
            This release is automatically compiled by GitHub Actions
          name: Tuinity Automation Compile ${{ steps.short_sha.outputs.sha_short }}
          draft: false
          tag_name: commit-${{ steps.short_sha.outputs.sha_short }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_KEY }}
          GITHUB_REPOSITORY: LangZongz/Tuinity
